[package]

name = "ecs"
version = "0.1.1"
authors = ["Tom Bebbington <tophattedcoder@gmail.com>"]

[lib]

name = "ecs"
path = "src/lib.rs"

[[bin]]

name = "ecs"
path = "src/main.rs"
doc = false

[dependencies]
time = "*"